## You should change each of the following fields
## to customize your blog

title: "Kolten's Data Dive"
description: "Diving into data science topics to deepen understanding." 
author: Kolten Smith
author_description: "A satistics student at Brigham Young University" 

url: https://skolten27.github.io ## change this to https://yourusername.github.io
baseurl: /my-blog ## change this to the name of your blog repository
header_image: /assets/img/datasciencebg.jpg ## change your header image if you want

## Add your social media user names.  Github is required, the rest are optional
social:
    github: skolten27 ## required
    twitter: 
    facebook: 
    email: 
    linkedin: Kolten Smith
    youtube: 
    tumblr: 
    website: 



### Advanced Settings (don't change below unless you know what you are doing)

paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
    - title: Home
      url: /index.html
    - title: About
      url: /about




