[theme]
base="dark"  
primaryColor="#F63366"  # Vibrant pink
backgroundColor="#0E1117"  # Dark gray
secondaryBackgroundColor="#262730" # Light gray
textColor="#333333"  # Dark gray
font="sans serif"  
